name: Release and Publish
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: karin-plugin-adapter-icqq
          default-branch: main
      # Checkout
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      # Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
        if: ${{ steps.release.outputs.release_created }}
      # 创建npmrc文件
      - run: |
          echo "@icqqjs:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
      # Install dependencies
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
      # Build output
      - run: npm run build
        if: ${{ steps.release.outputs.release_created }}
      # devDependencies
      - run: npm run deldev
        if: ${{ steps.release.outputs.release_created }}
      # Publish to npm
      - run: npm run pub
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
